
const recipes = [
    { name: "Boiled egg", ingredients: ["Eggs", "Water"], steps: ["Fill a pot with enough water to cover the eggs you want to cook.", "Place the pot on the stove and heat the water until it boils.", "Carefully lower the eggs into the boiling water using a spoon or tongs.", "Boil the eggs for 6-7 minutes for soft-boiled eggs or 10-12 minutes for hard-boiled eggs.", "Remove the eggs from the water and place them in a bowl of cold water to cool before peeling."] },
    { name: "Fried rice", ingredients: ["Oil", "Garlic", "Onion", "Cooked rice", "Soy sauce", "Salt", "Pepper"], steps: ["Heat a small amount of oil in a wok or large frying pan over medium-high heat.", "Add minced garlic and diced onion and stir-fry until lightly browned.", "Add cooked rice and stir-fry until the rice is heated through and slightly crispy.", "Add any additional ingredients such as diced vegetables, cooked meat, or scrambled eggs and stir-fry until heated through.", "Season with soy sauce, salt, and pepper to taste."] },
    { name: "Adobo", ingredients: ["Water", "Vinegar", "Soy sauce", "Garlic", "Black peppercorns", "Meat (chicken or pork)", "Potatoes"], steps: ["In a pot, bring water, vinegar, soy sauce, minced garlic, and black peppercorns to a boil.", "Add your choice of meat (such as chicken or pork) and simmer for 30 minutes until the meat is cooked through.", "Add diced potatoes and continue to simmer for an additional 15 minutes until the potatoes are tender.", "Serve hot with steamed rice."] },
    { name: "Sinigang", ingredients: ["Water", "Meat (pork or fish)", "Tamarind soup mix", "Vegetables (kangkong, okra, eggplant)"], steps: ["In a pot, bring water to a boil.", "Add your choice of meat (such as pork or fish) and simmer for 30 minutes until the meat is cooked through.", "Add a packet of tamarind soup mix and your choice of vegetables (such as kangkong, okra, and eggplant). Simmer for an additional 15 minutes until the vegetables are tender.", "Serve hot with steamed rice."] },
    { name: "Tinola", ingredients: ["Oil", "Garlic", "Onion", "Ginger", "Meat (chicken)", "Water", "Potatoes", "Green papaya or chayote"], steps: ["Heat a small amount of oil in a pot over medium-high heat.", "Add minced garlic, diced onion, and sliced ginger and stir-fry until lightly browned.", "Add your choice of meat (such as chicken) and stir-fry until browned on all sides.", "Add water and diced potatoes. Bring to a boil then reduce heat to low and simmer for 15 minutes until the potatoes are tender.", "Add sliced green papaya or chayote and continue to simmer for an additional 10 minutes until tender. Serve hot with steamed rice."] },
    { name: "Pancit", ingredients: ["Oil", "Garlic", "Onion", "Meat (chicken or pork)", "bihon noodles", "water", "vegetables (carrots, snow peas, cabbage)"], steps: ["Heat a small amount of oil in a wok or large frying pan over medium-high heat.", "add minced garlic, diced onion, and your choice of meat (such as chicken or pork) and stir-fry until lightly browned.", "add bihon noodles and enough water to cover the noodles. Bring to a boil then reduce heat to low and simmer until the noodles are softened.", "add your choice of vegetables (such as sliced carrots, snow peas, and cabbage) and stir-fry until tender. Serve hot."] }
  ]
  
export default recipes

